spring:
  #静态资源处理
  resources:
    #启用默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        #缓存响应时间，单位秒
        max-age: 3600
    chain:
      #资源链中启用缓存，默认启用
      cache: true
      #启用资源链，默认禁用
      enabled: true
      # 启用压缩资源(gzip,brotli)解析,默认禁用
      compressed: true
      #启用H5应用缓存，默认禁用
      html-application-cache: true
      #静态资源位置
    static-locations: classpath:/static/
  # thymelaef配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
    hikari:
      # 连接池名
      pool-name: DateHikarCP
      # 最小空闲链接
      minimum-idle: 5
      # 空闲链接最大时间
      idle-timeout: 1800000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的链接自动提交
      auto-commit: true
      # 链接最大存活时间
      max-lifetime: 1800000
      # 链接超时时间
      connection-timeout: 30000
      # 测试链接可用的查询语句
  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: 192.168.1.116
    #服务器端口
    port: 6379
    #数据库
    database: 0
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
  #RabbitMQ
  rabbitmq:
    #服务器地址
    host: 192.168.1.116
    #用户名
    username: admin
    #密码
    password: password
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间 默认1000ms
        initial-interval: 1000
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000
        #重试间隔的乘数。比如配2.0 第一次等10s，第二次等20s，第三次等40s
        multiplier: 1.0

# mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.xxx.seckill.pojo

# Mybatis SQL打印 （方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.xxx.seckill.mapper: debug
